---
swagger: "2.0"
info:
  description: "A modern contest platform for the modern web.\n"
  version: "1.0.0"
  title: "DMOJ REST API"
  license:
    name: "GNU Affero General Public License v3.0"
    url: "https://raw.githubusercontent.com/DMOJ/judge/master/LICENSE"
host: "localhost:8001"
basePath: "/"
schemes:
- "https"
- "http"
paths:
  /submit:
    post:
      tags:
      - "submit"
      summary: "Submit a solution to the judge"
      operationId: "add_submission"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Submission data"
        required: true
        schema:
          $ref: "#/definitions/Submission"
      responses:
        200:
          description: "successful operation"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "dmoj.rest"
  /runtimes:
    get:
      tags:
      - "runtimes"
      summary: "Retrieve all available language runtimes"
      operationId: "get_all_runtimes"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
      x-swagger-router-controller: "dmoj.rest"
  /problems:
    get:
      tags:
        - "problems"
      summary: "Retrieve all available problems at Judge"
      operationId: "get_all_problems"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
      x-swagger-router-controller: "dmoj.rest"
definitions:
  Submission:
    type: "object"
    required:
    - "languageId"
    - "problemId"
    - "sourceCode"
    properties:
      problemId:
        type: "string"
        description: "id of problem to grade"
      languageId:
        type: "string"
        description: "language of problem to grade"
      sourceCode:
        type: "string"
        format: "base64"
        description: "the source code to grade"
      timeLimit:
        type: "number"
        description: "time limit for grading, in seconds"
      memoryLimit:
        type: "integer"
        format: "int64"
        description: "memory limit for grading, in kilobytes"
        default: 65536
    example:
      timeLimit: 1
      sourceCode: "aW1wb3J0IGphdmEuaW8uKjsKCnB1YmxpYyBjbGFzcyBUZXN0IHsKICAgIHB1YmxpYyBzdGF0aWMgdm9pZCBtYWluKFN0cmluZ1tdIGFyZ3MpIHRocm93cyBFeGNlcHRpb24gewogICAgICAgIEJ1ZmZlcmVkUmVhZGVyIGJyID0gbmV3IEJ1ZmZlcmVkUmVhZGVyKG5ldyBJbnB1dFN0cmVhbVJlYWRlcihTeXN0ZW0uaW4pKTsKICAgICAgICBpbnQgbiA9IEludGVnZXIucGFyc2VJbnQoYnIucmVhZExpbmUoKSk7CiAgICAgICAgCiAgICAgICAgd2hpbGUgKG4tLSAhPSAwKSB7CiAgICAgICAgICAgIFN0cmluZ1tdIGFiID0gYnIucmVhZExpbmUoKS5zcGxpdCgiICIpOwogICAgICAgICAgICBTeXN0ZW0ub3V0LnByaW50bG4oSW50ZWdlci5wYXJzZUludChhYlswXSkgKyBJbnRlZ2VyLnBhcnNlSW50KGFiWzFdKSk7CiAgICAgICAgfQogICAgfQp9Cg=="
      languageId: "JAVA8"
      memoryLimit: 1024
      problemId: "aplusb"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
